package kernel;
import fs;
import types;

typedef types.uint32_t u32;
typedef types.uint64_t u64;

extern void kprintf(const char *fmt, ...);

/* Rootfs blob symbols emitted by user/blob.asm. */
extern char user_init_start;
extern char user_init_end;
extern char user_sh_start;
extern char user_sh_end;
extern char user_hello_start;
extern char user_hello_end;
extern char user_cat_start;
extern char user_cat_end;
extern char user_ls_start;
extern char user_ls_end;
extern char user_kbuild_start;
extern char user_kbuild_end;
extern char user_ldfake_start;
extern char user_ldfake_end;
extern char user_dumpbin_start;
extern char user_dumpbin_end;
extern char motd_start;
extern char motd_end;
extern char environ_start;
extern char environ_end;

/* Generated by tools/m5_stage.sh -> build/m5blob.asm: one entry per staged
 * bootstrap file (native compiler, sources, reference objects, asm blobs). */
struct m5_blob_entry {
    const char *path;
    const char *start;
    const char *end;
};
extern struct m5_blob_entry m5_blob_table[];
extern u64 m5_blob_count;

static void publish_one(const char *path, u64 start, u64 end) {
    u64 size = end - start;
    if (start == 0 || size == 0 || !fs.fs_publish_file(path, start, size)) {
        kprintf("[FS] FAILED to publish %s\n", path);
        return;
    }
    kprintf("[FS] published %s (%u bytes)\n", path, size);
}

/* Release every embedded user image into the Ramfs root, creating the
 * intermediate /bin and /etc directories. Runs once after fs_init(). */
void rootfs_publish(void) {
    u64 i;
    u32 ok = 0;

    publish_one("/bin/init",  (u64)(&user_init_start),  (u64)(&user_init_end));
    publish_one("/bin/sh",    (u64)(&user_sh_start),    (u64)(&user_sh_end));
    publish_one("/bin/hello", (u64)(&user_hello_start), (u64)(&user_hello_end));
    publish_one("/bin/cat",   (u64)(&user_cat_start),   (u64)(&user_cat_end));
    publish_one("/bin/ls",    (u64)(&user_ls_start),    (u64)(&user_ls_end));
    publish_one("/bin/kbuild", (u64)(&user_kbuild_start), (u64)(&user_kbuild_end));
    publish_one("/bin/ldfake", (u64)(&user_ldfake_start), (u64)(&user_ldfake_end));
    publish_one("/bin/dumpbin", (u64)(&user_dumpbin_start), (u64)(&user_dumpbin_end));
    publish_one("/etc/motd",  (u64)(&motd_start),       (u64)(&motd_end));
    /* fakecc reads its package search path from /proc/self/environ (its
     * getenv opens this exact path); point it at the in-OS source root so
     * `cd /src && fakecc ...` resolves the kernel packages. */
    publish_one("/proc/self/environ",
                (u64)(&environ_start), (u64)(&environ_end));

    /* Writable scratch directory for compiler outputs. */
    if (!fs.fs_mkdir("/tmp")) {
        kprintf("[FS] FAILED to publish /tmp\n");
    }

    for (i = 0; i < m5_blob_count; i++) {
        u64 msize = (u64)m5_blob_table[i].end - (u64)m5_blob_table[i].start;
        if (fs.fs_publish_file(m5_blob_table[i].path,
                              (u64)m5_blob_table[i].start, msize)) {
            ok++;
        } else {
            kprintf("[FS] FAILED to publish %s\n", m5_blob_table[i].path);
        }
    }
    kprintf("[FS] published %u staged bootstrap files\n", ok);
}
